name: Deploy to GitHub Pages

on:
  push:
    branches:
      - connect4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.0

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        run: |
          git config --global user.email "${{ secrets.GH_EMAIL }}"
          git config --global user.name "${{ secrets.GH_USERNAME }}"
          set -e  # Beenden Sie den Workflow bei Fehlern
          if ! git show-ref --verify --quiet "refs/heads/gh-pages"; then
            git checkout --orphan gh-pages
            git commit --allow-empty -m "Initialize gh-pages branch"
            git push -f origin gh-pages
          fi
          # Kopieren Sie Ihre Build-Dateien und verwenden Sie actions/gh-pages
          cp -r build/. .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
